eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
server:
  port: 9002
spring:
  application:
    name: ihrm-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm
    username: root
    password: asdqwe446
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
jwt:
  config:
    key: i4h4r4
    ttl: 360000


#?useUnicode=true&characterEncoding=utf8